### ISSUE TITLE
3. Metodologia

### ISSUE THREAD

**Issue by Milton-Ventura** [ICEI-PUC-Minas-PMV-ADS/pmv-ads-2024-1-e1-proj-web-t09-pmv-ads-2024-1-e1-projservicein#4]

**Comment by sara-gracielle** [comment]
Etapa 'Metodologia' concluída.

**Comment by sara-gracielle** [comment]
Etapa 'Metodologia: Gerenciamento (Divisão de Papéis, Processo, Etiquetas, Ferramentas, Estratégia de Organização de Codificação)'
